# include "../../includes/minishell.h"

/*DESCRIPTION DE LA FONCTION*/
void	interruption_handler(int signum)
{
	//suppress the "unused variable" warning, indicating that the 
	//signum parameter is not being used in the function.
	(void) signum;
	//prints a newline character to the terminal. This is done to ensure 
	//that the program's output appears on a new line after the user presses Ctrl+C.
	printf("\n");
	//informs Readline that a new line has started. This is typically used to maintain
	//proper command line editing and input handling.
	rl_on_new_line();
	//clears the current input line. It replaces the contents of the input line with 
	//an empty string.
	// instructs Readline to redisplay the prompt and the cleared input line. This is
	//necessary to ensure the terminal is in the correct state after the SIGINT signal.
	rl_redisplay();
}

/*If the SIGINT signal (Ctrl+C) is pressed, the interruption_handler
takes care of it. 
If the SIGQUIT signal (Ctrl+\) is pressed, nothing happens (it is
ignored).*/
void	signals(void)
{
	signal(SIGINT, interruption_handler);
	//sets up a signal handler for the SIGQUIT signal. However, in this case, it uses
	//SIG_IGN, which means the SIGQUIT signal is ignored. The SIGQUIT signal is typically
	//generated by pressing Ctrl+\ and is used for quitting the program while also generating
	//a core dump. By ignoring it, the program avoids the default behavior of quitting and
	//generating a core dump when Ctrl+\ is pressed.
	signal(SIGQUIT, SIG_IGN);
}
